/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-forgotten-knight-d14eb14d83bd4e7ba7cbe443d76a10fd
Title: ⛨ The Forgotten Knight ⛨
*/

"use client"

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Warrior(props) {
  const { nodes, materials } = useGLTF('models/warrior-transformed.glb');

  const modelRef = useRef();

  useFrame((state, delta, XRFrame)=>{

    // console.log(state.clock)
   modelRef.current.position.y = -1.8 + Math.sin(state.clock.elapsedTime)*0.15;
  })
  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[0,-1.5,0]}
    scale={[1.35,1.30,1.35]}
    rotation={[0.25,0,0]}>
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.roses_mat}
        position={[0.248, 1.783, 0.363]}
        rotation={[2.443, -1.393, -0.88]}
        scale={0.496}
      />
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh
        name="Object_10"
        geometry={nodes.Object_10.geometry}
        material={materials.cloak_mat}
        skeleton={nodes.Object_10.skeleton}
      />
      <skinnedMesh
        name="Object_12"
        geometry={nodes.Object_12.geometry}
        material={materials.center_armor_mat}
        skeleton={nodes.Object_12.skeleton}
      />
      <skinnedMesh
        name="Object_14"
        geometry={nodes.Object_14.geometry}
        material={materials.center_armor_mat}
        skeleton={nodes.Object_14.skeleton}
      />
      <skinnedMesh
        name="Object_16"
        geometry={nodes.Object_16.geometry}
        material={materials.eye_plug_mat}
        skeleton={nodes.Object_16.skeleton}
      />
      <skinnedMesh
        name="Object_18"
        geometry={nodes.Object_18.geometry}
        material={materials.top_armor_mat}
        skeleton={nodes.Object_18.skeleton}
      />
      <skinnedMesh
        name="Object_20"
        geometry={nodes.Object_20.geometry}
        material={materials.top_armor_mat}
        skeleton={nodes.Object_20.skeleton}
      />
      <skinnedMesh
        name="Object_22"
        geometry={nodes.Object_22.geometry}
        material={materials.bottom_armor_mat}
        skeleton={nodes.Object_22.skeleton}
      />
      <skinnedMesh
        name="Object_24"
        geometry={nodes.Object_24.geometry}
        material={materials.center_armor_mat}
        skeleton={nodes.Object_24.skeleton}
      />
      <skinnedMesh
        name="Object_25"
        geometry={nodes.Object_25.geometry}
        material={materials.details_mat}
        skeleton={nodes.Object_25.skeleton}
      />
      <skinnedMesh
        name="Object_27"
        geometry={nodes.Object_27.geometry}
        material={materials.center_armor_mat}
        skeleton={nodes.Object_27.skeleton}
      />
      <skinnedMesh
        name="Object_28"
        geometry={nodes.Object_28.geometry}
        material={materials.details_mat}
        skeleton={nodes.Object_28.skeleton}
      />
      <skinnedMesh
        name="Object_29"
        geometry={nodes.Object_29.geometry}
        material={materials.top_armor_mat}
        skeleton={nodes.Object_29.skeleton}
      />
      <skinnedMesh
        name="Object_31"
        geometry={nodes.Object_31.geometry}
        material={materials.details_mat}
        skeleton={nodes.Object_31.skeleton}
      />
      <mesh
        name="Object_103"
        castShadow
        receiveShadow
        geometry={nodes.Object_103.geometry}
        material={materials.sword_mat}
        position={[0, 1.844, 0.392]}
      />
    </group>
  )
}

useGLTF.preload('models/warrior-transformed.glb')
